---
- hosts: localhost
  vars:
    storage_role: cdi
  connection: local
  gather_facts: False
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
    - role: "{{ storage_role }}"

